### PR TITLE
build: use vite for bundling and remove vue cli

### PR DESCRIPTION
**Pull request by luqven**
# Description

This PR transitions this library from the vue-cli and instead uses Vite and Vitest to bundle, serve, and test files.

### Things to note
- Third-party licenses had to be stored in a separate file and referenced in a top-of-file comment in the `/dist` files. This is a limitation of how esbuild, which Vite uses, strips comments.
- The LTS Node version (as of now) was the `target` Vite build version. This was to avoid breaking changes for users on ECMA Script versions older than "modern" or "evergreen" browsers.
- `dist/` was checked in _only_ to demonstrate how the bundling changes affect comments. They should get removed before merging (outside of the **deleted** dist files, which are not actually needed anymore AFAIK).
- `concurrently` needed the `succeed` flag to tell it not to error when `vite dev` was killed

## TODO
- [x] rewrite tests in `vitest` so that we can
	- [x] remove `@vue/cli-plugin-babel/preset` dep
	- [x] remove `@vue/cli-plugin-unit-jest` dep
	- [x] remove `@vue/cli-shared-utils` dep

### CODE REVIEW

**Comment by mdunbavan** [comment]
@luqven how's it going? Do you need help with moving this along at all?

**Comment by luqven** [comment]
> @luqven how's it going? Do you need help with moving this along at all?

We don't have plans to tackle this just yet, but we would welcome contributions! 

If this sounds like something you'd like to take up, tag me and let us know. Happy to provide reviews/guidance as needed.

**Comment by mdunbavan** [comment]
> > @luqven how's it going? Do you need help with moving this along at all?
> 
> We don't have plans to tackle this just yet, but we would welcome contributions!
> 
> If this sounds like something you'd like to take up, tag me and let us know. Happy to provide reviews/guidance as needed.

@luqven if you let me know what needs doing I would be happy to help.

It is something I need for a project that I am working on.

**Comment by luqven** [comment]
@mdunbavan Apols for the delay here, some other things demanded all of my time for a good while.

I've gone ahead and updated this PR move to make this task a little easier. I've also added some `TODO`s. Please feel free to pick one (or more!) and ping me if you want to work on it. I recommend you "stack" any PR on top of this one.

In the meantime, we'll continue to tackle this as time permits. Especially important now that Node v20 is out.

**Pull request merged**
